#Alexander 10/03/2025
print("________________________________________________________________________________________________")
print("|                                                                               10/Marzo/2025  |")
print("|                                                                              Santiago-Chile  |")
print("|                                                                                              |")
print("|    Futuro Alex                                                                               |")
print("|                                                                                              |")
print("|    Fue estresante escribir esta carta pero se pudo que es lo importante.                     |")
print("|    Ahora mismo estoy aburrido, quiero acabar luego este año y empezar rapido en mi futuro.   |")
print("|    Quiero aprender a codificar paginas web muy importantes o utiles en la vida de todas      |")
print("|    las personas                                                                              |")
print("|    Espero haber terminado con buen promedio este año, y tmb con amigos si es q se puede.     |")
print("|                                                                                              |")
print("|                                                                                              |")
print("|______________________________________________________________________________________________|")